apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: push-image-buildah-
spec:
  serviceAccountName: build-bot
  params:
    - name: app-name
      value: express-sample-app
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/emea-7-hufnagel-kustomize-trigger
    - name: image-repo
      value: quay.io/christian_hufnagel/express-sample-app
  pipelineRef:
    name: push-image-buildah
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce 
          resources:
            requests:
              storage: 1Gi